apiVersion: v1
kind: Namespace
metadata:
  name: custos
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: custos-daemon
  namespace: custos
  labels:
    app: custos-daemon
spec:
  selector:
    matchLabels:
      name: custos-daemon
  template:
    metadata:
      labels:
        name: custos-daemon
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: custos-daemon
        image: docker.io/custos/daemon:0.1.0
        imagePullPolicy: IfNotPresent
        command:
        - "/usr/local/bin/custos-k8s-daemon"
        args:
        - "--interface"
        - "eth0"
        - "--queue-id"
        - "0"
        - "--socket-path"
        - "/var/run/custos/custos.sock"
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN # Required for loading/attaching eBPF program to interface
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsUser: 0 # Must run as root to perform network & eBPF operations
        volumeMounts:
        - name: socket-dir
          mountPath: /var/run/custos
        - name: hugepages
          mountPath: /dev/hugepages
      volumes:
      - name: socket-dir
        hostPath:
          path: /var/run/custos
          type: DirectoryOrCreate
      - name: hugepages
        hostPath:
          path: /dev/hugepages
          type: Directory
